# Build and run unit tests
name: CI

on: [ push, pull_request ]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        dc: [ ldc-master, ldc-latest, ldc-1.25.0, dmd-latest, dmd-2.090.1 ]
        exclude:
          # https://github.com/dlang/dub/issues/1914
          # https://github.com/dlang/dub/issues/1915
          - { os: windows-latest, dc: dmd-latest }
          - { os: windows-latest, dc: dmd-2.090.1 }

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: 'Build & Test'
      if: runner.os != 'Windows'
      run: |
        dub test --compiler=$DC
        dub test -c unittest-with-deps --compiler=$DC

    - name: '[Windows] Build & test'
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        dub test --compiler=${{ env.DC }}
        if %errorlevel% neq 0 exit /b %errorlevel%
        dub test -c unittest-with-deps --compiler=${{ env.DC }}
        if %errorlevel% neq 0 exit /b %errorlevel%

    - name: 'Upload code coverage'
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
